---
version: 0.2

phases:
  install:
    commands:
      # Debugging
      - env | sort
      # Work inside GOPATH
      - ln -s ${CODEBUILD_SRC_DIR} ${SRC_DIR}
      - cd ${SRC_DIR}
      # Debugging
      - pwd
      - find .
      # Install dependencies
      - make install

  pre_build:
    commands:
      # Run all tests included with the application
      - make test

  build:
    commands:
      # Build the go application
      - make build
      # Package the application with AWS SAM using $S3_BUCKET
      - make package

artifacts:
  files:
    # Name of the executable
    - handler
    # Zipped up executable
    - handler.zip